name 'cb-reverse-proxy'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures cb-reverse-proxy'
long_description 'Installs/Configures cb-reverse-proxy'
version '0.1.0'
